### ISSUE TITLE
Broken in Redmine 6.0.1 

### ISSUE THREAD

**Issue by Grovkillen** [farend/redmine_theme_farend_bleuclair#99] opened 2024-11-30 14:28 UTC
I've installed Redmine 6 and the theme is broken. Please see image below:

![image](https://github.com/user-attachments/assets/3e20ee4c-a59d-4cac-8b49-6f0f5a16a898)

**Comment by Grovkillen** [comment] 2024-12-01 13:24
Ok, I got it working by making a bit of a hack since the new file structure for themes in Redmine isn't 100% bullet proof.

First I needed to do some redirect in the nginx.config:

```
# Needed MIME-types
types {
	text/css css;
	application/javascript js;
}

# CSS files
location ~ ^/assets/themes/(.+?)/(.+?)\.css$ {
	alias /usr/share/redmine/themes/$1/stylesheets/$2.css;
	access_log off;
	expires max;
}

# JavaScript files
location ~ ^/assets/themes/(.+?)/(.+?)\.js$ {
	alias /usr/share/redmine/themes/$1/javascripts/$2.js;
	access_log off;
	expires max;
}
```

After that I needed to add the default.css into the themes folder (just copied the standard css code into default.css), and then made the application.css file look like this:

```
@import url(./default.css);
@import url(./theme.css);
```

![image](https://github.com/user-attachments/assets/3fda18d1-3921-4a26-b021-37ddc6a1bde1)

**Comment by peter-hank** [comment] 2024-12-03 22:40
I have the same problem, it doesn't load the theme.

> After that I needed to add the default.css into the themes folder (just copied the standard css code into default.css), and then made the application.css file look like this:

Better to create a symlink to the default theme stylesheet, this will help to keep it up-to-date when new Redmine updates arrive.

Redmine tries to load the theme from `/assets/themes/custom_theme_name/application.css`. Which is weird because the [Redmine Wiki](https://www.redmine.org/projects/redmine/wiki/Themes) says that it should load `/assets/themes/custom_theme_name/stylesheets/application.css`.

**Comment by ishikawa999** [comment] 2024-12-03 23:53
@Grovkillen @peter-hank 
<img width="1138" alt="screenshot 2024-12-04 8 38 27" src="https://github.com/user-attachments/assets/e0aa1bee-4063-4db1-b968-3717b935bdb3">
I am able to use a combination of Redmine 6.0.1 and Bleuclair 1.0.2 in my environment and cannot reproduce the problem.
Could you please give me some information to reproduce the problem?

Information that would be nice to get:
- How you are building Redmine (if you have any reference steps, etc.)
- The directory where you installed bleuclair
- The steps you took when you installed the theme
- Are there any errors in the browser's developer tools?
- Is the URL in the format like `https://<<url>>` ? Or is it in the format like `https://<<url>>/<<subdirectory>>`?

**Comment by ishikawa999** [comment] 2024-12-04 05:09
Note that the directory to place themes has changed to `/your/path/redmine/themes/bleuclair` since Redmine6.
(It does not work well in /assets/themes/bleuclair or public/themes/themes/bleuclair)

**Comment by Grovkillen** [comment] 2024-12-04 05:33
Yes, I installed tkr theme in the root/themes folder as per the information I got for the 6 version. I will try to get you a step by step procedure of how I set the server up.

**Comment by ishikawa999** [comment] 2024-12-04 05:51
> Yes, I installed the theme in the root/themes folder as per the information I got for the 6 version. I will try to get you a step by step procedure of how I set the server up.

Thanks for your support.
The directory where you have the theme installed looks fine.

**Comment by peter-hank** [comment] 2024-12-04 09:17
@ishikawa999 

Using the latest Docker image of [Redmine (6.0.1)](https://hub.docker.com/_/redmine) you can reproduce the issue.

Just run the image, use `git clone https://github.com/farend/redmine_theme_farend_bleuclair.git themes/bleuclair` to clone the theme, set it in the admin and you should see it.

Their default Docker Compose config file is broken, use this one:
```
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```

It will be on 8080, then admin/admin to login to the admin panel.

**Comment by peter-hank** [comment] 2024-12-04 09:38
Adding the themes folder to the assets pipeline seems to help.

https://github.com/redmine/redmine/blob/master/config/initializers/30-redmine.rb#L29

So instead of:
``` 
default_paths << Rails.root.join("app/assets/stylesheets")
Rails.application.config.assets.redmine_default_asset_path = Redmine::AssetPath.new(Rails.root.join('app/assets'), default_paths)
```
we need:
```
default_paths << Rails.root.join("app/assets/stylesheets")
default_paths << Rails.root.join("themes")
Rails.application.config.assets.redmine_default_asset_path = Redmine::AssetPath.new(Rails.root.join('app/assets'), default_paths)
```

Looks like an issue with Redmine, not the theme itself and it's interesting that it works on your setup @ishikawa999.

**Comment by ishikawa999** [comment] 2024-12-04 23:49
> @ishikawa999
> 
> Using the latest Docker image of [Redmine (6.0.1)](https://hub.docker.com/_/redmine) you can reproduce the issue.
> 
> Just run the image, use `git clone https://github.com/farend/redmine_theme_farend_bleuclair.git themes/bleuclair` to clone the theme, set it in the admin and you should see it.
> 
> Their default Docker Compose config file is broken, use this one:
> 
> ```
> version: '3.1'
> 
> services:
> 
>   redmine:
>     image: redmine
>     restart: always
>     ports:
>       - 8080:3000
>     environment:
>       REDMINE_DB_MYSQL: db
>       REDMINE_DB_PASSWORD: example
> 
>   db:
>     image: mysql:8.0
>     restart: always
>     environment:
>       MYSQL_ROOT_PASSWORD: example
>       MYSQL_DATABASE: redmine
> ```
> 
> It will be on 8080, then admin/admin to login to the admin panel.

@peter-hank 

I was able to reproduce the problem. Thank you for taking the time to document it.
I resolved the issue on my end by restarting the container after adding the theme. Could you please try the same and let me know if it works?

**Comment by ishikawa999** [comment] 2024-12-04 23:57
Alternatively, you can solve this problem by installing the theme before starting the rails server.

```
# docker-compose.yml
version: '3.1'

services:

  redmine:
    build:
      context: .
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```

```
# Dockerfile
FROM redmine:6.0.1

RUN git clone --depth=1 https://github.com/farend/redmine_theme_farend_bleuclair.git themes/bleuclair
```

**Comment by peter-hank** [comment] 2024-12-05 10:58
@ishikawa999

Restating the server is not enough in my case. What helps is compiling the app assets with `rails assets:precompile`.

> Alternatively, you can solve this problem by installing the theme before starting the rails server.

This works because the container compiles the assets on restart.

**Comment by Grovkillen** [comment] 2024-12-05 16:22
This has been addressed here: https://www.redmine.org/issues/41754

**Comment by ishikawa999** [comment] 2024-12-06 00:21
Thanks for the information.
It does not seem to be a problem on the theme side, so I will close the issue. If you need additional support, please reopen the issue.

**Closed by ishikawa999** 2024-12-06 00:22 UTC
